version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  # 1. 使用 apt 安装 git-lfs
  apt_packages:
    - git-lfs
  # 2. 在构建前执行命令：安装 LFS 钩子并拉取文件
  jobs:
    pre_build:
      - git lfs install
      - git lfs pull

sphinx:
  configuration: source/conf.py

python:
  install:
    - requirements: requirements.txt